### ISSUE TITLE
Comment counter missing

### ISSUE THREAD

**Issue by catflinger** [fifteensquared/fifteensquared-theme#14]
v1.0.4 installed in sandbox. #comments anchor working but this has highlighted that there is something missing. Between the post footer and the start of the comments there should be a line:

xx Responses to "post-title"

On the live site the #comments anchor scrolls to this line. This line may have been missing before and I failed to notice the omission because the comments link wasn't working.

**Comment by catflinger** [comment]
Fix in 1.0.5. Needs testing.

**Comment by Walahfrid** [comment]
1.0.5 installed in the sandbox. The xx Responses to "post-title" issue appears to have been resolved, though there is now a No Responses to "post-title" on posts with no comments which doesn't appear on the live site. This is not a problem.

I will thoroughly test 1.0.5 later today.

**Comment by Walahfrid** [comment]
1.0.5 tests completed, one anomaly found.

When using the comments link in a post footer, most of the time it displays the xx Responses to "post-title" at the top of the screen followed by the first few comments. However, occasionally the xx Responses to "post-title" appears at the bottom of the screen with the last part of the post above it.

This behaviour is not consistent and is difficult to repeat to try and find the cause. For example, on one post with a lot of comments the 'xx Responses to' was at the bottom of the screen. I returned to the Home page and clicked on the same comments link again. This time the 'xx Responses to' was at the top of the screen.

It doesn't seem to depend on the type of post (simple, table etc) nor on the number of comments (above the minimum necessary to cause the end of the post to scroll off the screen). We could probably live with this bug but if it can be easily rectified then that would be preferable.

**Comment by catflinger** [comment]
So the page always has the correct content and layout, it is just the scroll position that varies.  Is that correct?

**Comment by Walahfrid** [comment]
Yes.

**Comment by catflinger** [comment]
I can't reproduce this.

I have followed the comments link in the post footer using various browsers in the sandbox and in live.  It worked reliably every time.  It also works OK on my local Wordpress install at home.

The only thing I could find was that when I signed in the Wordpress Admin toolbar overlays the response count header so the heading was not visible.  The first time this happened I initially thought I had seen the behaviour but I had mistaken the "Leave a reply" heading showing at the bottom of the screen for the expected "Responses to" heading.

**Comment by Walahfrid** [comment]
I have just tried the sandbox again and have found the same issue in both IE11 and Edge. I selected the Guardian category and then worked my way down the page, clicking on the comment link in each post footer. It wasn't long before I found a post where the Responses line was at the bottom of the page. With Edge, when I found the error I retried the same post. The Responses line was still at the bottom of the screen. A third attempt on this post gave the correct display.

Using Chrome on my laptop resulted in the correct display every time. However, there was still an anomaly. On some occasions the Norton toolbar, which reloads after the page has loaded, overwrote the xx Responses line, on other occasions the page scrolled down after the toolbar appeared and so the xx Responses line was visible at the top of the screen. This does not happen on the live site where the page always moves down to display the xx Responses line when the Norton toolbar reloads.

Repeating the test on the live site using IE11 gave no errors, the xx Responses line always appeared at the top of the screen.

**Comment by catflinger** [comment]
I can't reproduce this following your steps.

Using IE11 I scrolled through The Guardian category following the comments link on each post summary.  I tried 100 or so posts on each of the live and the sandbox.  I didn't see this behaviour happen.

I did notice that on the sandbox the page first displays the entire post from the top and the after a short pause repositions the view to the comments count.  On the live system I only saw the post positioned at the comment count.  If there was a previous position loaded then it was replaced too quickly for me to see it.

There was one instance testing on the sandbox when I was not sure what had happened.  I saw a grid image which meant that the comment count could not have been at the top.  Unfortunately I was on autopilot by this stage and had already clicked the back button before I could verify what I had thought I saw.  Perhaps I was just remembering the previous whole post that had flashed up longer then usual this time.  I retried this post over and over and it worked correctly every time.

**Comment by catflinger** [comment]
My only idea at the moment is that the behaviour is being caused by an timing problem.  The position of the view is getting set two ways:

The hashtag in the url causes the view to be positioned at the first element in the html with an ID that matches the tag

A browser extension uses Javascript to add additional elements into the document (to display a toolbar for example) and repositions the view to take account of the new content.

Maybe there is a timing issue where under certain circumstances these events happen in an unexpected order and produce an unexpected result.

I don't see the problem because I test in a different environment.  Different browser extensions, different processor and Internet connection speeds.

**Comment by catflinger** [comment]
Closing as comment counter now shows.

View positioning problem continued on new issue.
