### ISSUE TITLE
Unexpected view positioning when following comments link

### ISSUE THREAD

**Issue by catflinger** [fifteensquared/fifteensquared-theme#16]
Moved from Comment Count issue

From Geoff:

When using the comments link in a post footer, most of the time it displays the xx Responses to "post-title" at the top of the screen followed by the first few comments. However, occasionally the xx Responses to "post-title" appears at the bottom of the screen with the last part of the post above it.

This behaviour is not consistent and is difficult to repeat to try and find the cause. For example, on one post with a lot of comments the 'xx Responses to' was at the bottom of the screen. I returned to the Home page and clicked on the same comments link again. This time the 'xx Responses to' was at the top of the screen.

It doesn't seem to depend on the type of post (simple, table etc) nor on the number of comments (above the minimum necessary to cause the end of the post to scroll off the screen). We could probably live with this bug but if it can be easily rectified then that would be preferable.

**Comment by Walahfrid** [comment]
You closed the previous issue just as I was halfway through typing a reply,

The sandbox always runs more slowly than the live site which is why you at times see the start of the post before it scrolls down to the xx Responses line.

I have repeated the tests, this time using my laptop. The issue was still there in IE11 but Edge seemed fine (unlike my desktop earlier), though it is the usual case that one more attempt may have proved otherwise.

If it were a timing error then surely the same problem would arise with the live site during periods when it has been responding more slowly than usual.

**Comment by catflinger** [comment]
Does desktop Edge have any extension active that you laptop does not?  The Norton tools you mentioned earlier for instance?

**Comment by Walahfrid** [comment]
My desktop Edge has the Norton Identity Safe extension and I imported favourites from IE11. From memory, these are the only changes I have made to it.

Today was the first time I have used Edge on my laptop and it wanted to refuse access to the sandbox site due to a supposed certificate error. I have not had this problem with the desktop Edge.

I have the full Norton IS add-ons installed in IE11 and Chrome.

**Comment by catflinger** [comment]
Sticking to Edge for the moment and ignoring the other browsers, are the desktop and the laptop installs the same?  I'm not clear at the moment whether you have exactly the same extensions on both browsers.

**Comment by Walahfrid** [comment]
Laptop bog standard Edge, desktop Edge plus Norton Identity Safe extension.

**Comment by catflinger** [comment]
If you disable all the extensions on the desktop browser does the misplaced view behaviour go away?  If you enable them again does it show again?

**Comment by Walahfrid** [comment]
Result the same as before both with and without the Norton extension. The problem appears to be more prevalent in Edge than in IE11 (I don't have to click on as many comment links for the placement error to appear). Repeated comment access on the same post can give either the correct or incorrect display.

**Comment by catflinger** [comment]
I don't have any more ideas what might cause this.  What I gather so far is:

1. It is a fact. We have seen it enough times to know it is not just a confusion or misreading of the events.
2. It is unpredictable.  We do not yet have a process that will reliably produce the symptoms.
3. The symptoms are environment related.  I view the same website using the same browsers and have not seen the symptoms at all.  You see different symptoms on different PCs.

I can try a few more PCs at our house to see if I can reproduce it here.  Other than that I have no more suggestions to make.

**Comment by catflinger** [comment]
I have now seen this happen by viewing the sandbox in Edge on my laptop instead of my desktop.  Out of about 100 tests I saw it happen twice.  Each time not repeatable.  In each case the post contained an image (this might be relevant).

The comments were shown beginning in the centre of the screen rather than at the top.  This did not look out of place (I was shown to the comments) and if I were not specifically testing for this anomaly I would probably not have noticed anything unusual had occurred.

**Comment by Walahfrid** [comment]
I have now tried desktop Edge more extensively in the live site. For the majority of the time the display after clicking the comments link was correct, xx Responses was at the top of the screen. However, there were five occasions when the xx Responses appeared in the middle of the screen with the end of the post above it and the first couple of comments below.

I have not seen the middle of the screen xx Responses in the sandbox, only top or bottom. I have not yet seen xx Responses at the bottom on the live site.

**Comment by catflinger** [comment]
One idea to pursue is that there is a timing issue around loading the image.  The browser initially shows the comments at the top of the page.  Sometimes the image is slow to load and when it does it pushes the comments further down the page.

I don't have much faith in this theory, but at least it could theoretically account for the symptoms observed.

**Comment by catflinger** [comment]
Looking at the page source I can see that the image in the blog does not have a height or width specified.  This means that at the time of loading the page the browser does not know how much space to leave in the page for the image,  When the browser gets the actually image it then re-renders the layout with space for the image now the actual size is known.

This would explain why the comments could move down the page after having been originally correctly positioned at the top.

**Comment by Walahfrid** [comment]
You could be right! I have just tried desktop Edge again on the sandbox site, prior to bringing up the developers' tools, and it took far more attempts to find an erroneous display than it did first thing this morning when the error appeared on the second or third post that I tried.

Regarding images, I have never noticed the misplacement of the xx Responses on one of Eileen's posts and she doesn't use images or have an avatar. I have noticed when there have been poor response times that the display of an avatar is often delayed and appears a short while after to post has been loaded.

**Comment by catflinger** [comment]
It makes sense that the symptoms will be maximised by a fast local processor and a slow server/connection.  This gives the best chance that the image arrives too late, after the page has been rendered.

**Comment by catflinger** [comment]
If this is the case then the theme is behaving correctly.  The problem is with the content of the blogs not the page that displays them.

I will try and create a couple oftest cases so we can test this theory .

**Comment by Walahfrid** [comment]
Please ignore the reference to Eileen's posts in my last comment. I have just had the xx Responses at the bottom of the screen on one of her posts. Also, though she doesn't have an avatar, there is a 1px x 1px image instead to suppress the IE red-cross error image.

**Comment by Walahfrid** [comment]
Please don't spend too long on this issue. So long as the xx Responses appears somewhere on the screen when the comments link is used then the link has done its job (it just looks neater and more professional if the xx Responses is at the top).

It would seem that this issue has probably been present on the live site for quite some time (for ever?) but has gone unnoticed until I was testing v1.0.5 in the sandbox. To be honest, I don't think I have ever used the comments link on the live site before this week because I always read comments in the WP dashboard.

**Comment by catflinger** [comment]
Closing this issue as it is already present on the live and the behaviour is considered acceptable.
