### ISSUE TITLE
Unwanted nbsp added by WYSIWYG editor

### ISSUE THREAD

**Issue by Walahfrid** [fifteensquared/fifteensquared-theme#19]
If someone hits 'return' at the end of the last line of a comment, the WYSIWYG editor adds the nbsp HTML on the following line which gives an unwanted blank space at the bottom of the comment when it is posted. The standard WP comment editor ignores any 'return' at the end of a comment.

**Comment by catflinger** [comment]
I would say the WYSIWYG editor has the most compliant behaviour: the user has requested another paragraph at the end of their comment and the editor has reliably provided one.

We could override this by hooking into Wordpress and editing the comment before it gets saved into the database, removing any blank-looking paragraphs at the end of a comment.  I think this would be quite do-able but would need some care, we could accidentally remove too much if we don't think carefully.

It is worth noting that technically this is not an appearance issue like the others.  This is a problem with the content of the comment, not how it is displayed.

**Comment by Walahfrid** [comment]
With the custom css for line spacing added, the extra blank line at the end of a comment is not so noticeable so I suggest that suppressing the nbsp waits until the next theme update.

**Comment by catflinger** [comment]
Treating this as covered by issue/enhancement 21 - remove trailing spaces
