### ISSUE TITLE
Incompatibility with Live Comment Preview plugin

### ISSUE THREAD

**Issue by fifteensquared** [fifteensquared/fifteensquared-theme#7]
Using Live Comment preview causes undefined variable "$id" entires in the debug log

**Comment by catflinger** [comment]
A fix is in version 1.0.1 but needs testing.

The code causing this was present in the original andreas09 theme, so has been there for years.  I am unsure how this code has ever worked but somehow it manages to add a comment successfully without generating an entry in the debug log when the comment preview is not present.

I have replaced $id with $post->ID which I think is what the author originally intended.

I am a little concerned that I still don't know why $id didn't raise an error without comment preview present.

**Comment by catflinger** [comment]
Closing as not currently intending to use comment preview.
